FROM python:3.13-slim

WORKDIR /bot
COPY ./telegram-bot/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./telegram-bot/config.py ./telegram-bot/infonayttobot.py ./

ENTRYPOINT ["python", "infonayttobot.py"]
